name: Quality Check
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run eslint
        run: yarn lint
      - name: Run TypeScript analysis
        run: yarn typecheck
